export enum ProductKind {
  TIGHTS_OR_STOCKING_200_DENIER = "TIGHTS_OR_STOCKING_200_DENIER",
  TIGHTS_OR_STOCKING_GIRLS_120_DENIER = "TIGHTS_OR_STOCKING_GIRLS_120_DENIER",
  TIGHTS_OR_STOCKING_20_OR_40_DENIER = "TIGHTS_OR_STOCKING_20_OR_40_DENIER",
  LACE_FAN_TIGHTS = "LACE_FAN_TIGHTS",
}
